version: '3.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wmfile 
    ports:
      - "3000:3000"
    networks:
      - wmfile-network
  

networks:
  wmfile-network:
    driver: bridge
